class ErrorCode:

    # CAPTCHA
    INVALID_CAPTCHA = "AUTH-001"
    CAPTCHA_EXPIRED = "AUTH-002"
    CAPTCHA_ALREADY_USED = "AUTH-003"

    # LOGIN
    INVALID_CREDENTIALS = "AUTH-004"
    USER_NOT_FOUND = "AUTH-005"
    USER_INACTIVE = "AUTH-006"
    USER_LOCKED = "AUTH-007"

    # OTP
    INVALID_OTP = "AUTH-008"
    OTP_EXPIRED = "AUTH-009"
    OTP_RETRY_EXCEEDED = "AUTH-010"

    # JWT
    INVALID_ACCESS_TOKEN = "AUTH-011"
    INVALID_REFRESH_TOKEN = "AUTH-012"
    SESSION_EXPIRED = "AUTH-013"

    # Validation
    VALIDATION_ERROR = "VAL-400"

    # Resource
    RESOURCE_NOT_FOUND = "RES-404"

    # Database
    DATABASE_ERROR = "DB-500"

    # Generic
    INTERNAL_SERVER_ERROR = "APP-500"